### ISSUE TITLE
HTML render issue with rack-dynamic-routes lab??

### ISSUE THREAD

**Issue by doosemavis** [learn-co-students/rack-dynamic-routes-lab-online-web-sp-000#407]
Had a student with this issue where they tried to run `open index.html` to open the file, and once loaded nothing was rendered onto the DOM.  

In the Canvas lesson it gives instructions that "you will be able to open `index.html` in your browser and add . . . etc".  But it's unsuccessful.  Also have noticed that the instructions on `learn-co-students/rack-dynamic-routes-lab-online` AND `learn-co-curriculum/rack-dynamic-routes-lab-online` README's both are missing those instructions.  Didn't know if this was a copy paste error or maybe just forgot to delete that portion in the README from Canvas possibly?  

Hope this is helpful!! 

@lizbur10 (Don't remember Blake's username for this one, haha)

**Comment by bal360** [comment]
Hey @doosemavis, 

I don't see anything about opening an `index.html` file in this labs instructions in Canvas. Are you certain it was this lab? There wouldn't be an `index.html` file for this lab in the first place, so that would definitely be something we want to remedy, but I just don't see that anywhere. 

I'm going to close this issue for now, but if you're able to provide a specific link to the students' Canvas page where those instructions exist then please open the issue again and send that our way!
